/* Requires the Docker Pipeline plugin */
pipeline {
    agent any
    stages {
        stage('build') {
            agent {
                docker {
                    // image 'golang:1.19.1-alpine'
                    dockerfile true
                    reuseNode true
                }
            }
            steps {
                sh 'go version'
            }
        }
        stage('test') {
            // agent {
            //     docker {
            //         image 'postgres:12.6'
            //     }
            // }
            steps {
                sh 'make test'
            }
        }
    }
}