/* Requires the Docker Pipeline plugin */
pipeline {
    agent {
        dockerfile {
            dir 'cloud'
        }
    }
    stages {
        stage('build') {
            // agent {
            //     dockerfile true
            //     reuseNode true
            // }
            steps {
                sh 'go version'
            }
        }
        stage('test') {
            // agent {
            //     docker {
            //         image 'postgres:12.6'
            //     }
            // }
            steps {
                sh 'make test'
            }
        }
    }
}